//
//  GeneratedPluginRegistrant.swift
//  Flutter
//
//  Generated by Flutter. DO NOT EDIT.
//

import Flutter
import UIKit
import GoogleMaps

@objc public class GeneratedPluginRegistrant: NSObject {
  @objc public static func register(with registrar: FlutterPluginRegistrantCallback) {
    if !registrar.isRegistered(for: GoogleMapsPlugin.self) {
      registrar.register(GoogleMapsPlugin())
    }
  }
}