//
//  GeneratedPluginRegistrant.swift
//  Flutter
//
//  Generated by Flutter.
//

import Flutter
import UIKit
import GoogleMaps

@objc class GeneratedPluginRegistrant: NSObject {
  @objc static func register(with registrar: FlutterPluginRegistrantCallback) {
    if !registrar.isRegistered(for: GoogleMapsPlugin.self) {
      registrar.register(GoogleMapsPlugin())
    }
  }
}